- type: entity
  parent:
  - BaseMob
  - MobCombat
  id: TFDPlayableSCP
  abstract: true
  save: false
  components:
  - type: Stamina
  - type: Damageable
    damageContainer: Biological
  - type: NoSlip
  - type: StatusEffects
    allowed:
    - Stun
    - KnockedDown
    - SlowedDown
  
  